[controller]
network_port = 52000
controller_port = 52004
consensus_port = 52001
storage_port = 52003
kms_port = 52005
executor_port = 52002
node_address = "0x3f05a198b46179aa54115ab246f07c9417ce9ec9"

[genesis_block]
timestamp = 1633765324292
prevhash = "0x0000000000000000000000000000000000000000000000000000000000000000"

[system_config]
version = 0
chain_id = "0x26b0b83e7281be3b117658b6f2636d0368cad3d74f22243428f5401a4b70897e"
admin = "0xe7b14f079c1db897568883f0323af5887c2feebb"
block_interval = 3
validators = [ "0x47bfe5185471c7ded9ead15e4c768202c6d561e6", "0xd15373d1a0365d8491f4bede2e2d3863cca8e45d", "0x3f05a198b46179aa54115ab246f07c9417ce9ec9", "0x2e3bef28673715063bdc3b82d9a33fa96f959811",]
block_limit = 100

[consensus]
node_addr = "0x3f05a198b46179aa54115ab246f07c9417ce9ec9"
grpc_listen_port = 52001
network_port = 52000
controller_port = 52004

[network_p2p]
port = 40002
grpc_port = 52000

[[network_p2p.peers]]
address = "/ip4/127.0.0.1/tcp/40000"

[[network_p2p.peers]]
address = "/ip4/127.0.0.1/tcp/40001"

[[network_p2p.peers]]
address = "/ip4/127.0.0.1/tcp/40003"

[kms_sm]
kms_port = 52005

[storage_rocksdb]
kms_port = 52005
storage_port = 52003

[executor_evm]
executor_port = 52002
[network_tls]
ca_cert = """
-----BEGIN CERTIFICATE-----\r
MIIBbTCCARKgAwIBAgIIOYrSF77doEYwCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwW\r
cmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEw\r
MTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDBZMBMG\r
ByqGSM49AgEGCCqGSM49AwEHA0IABGTl2glsbjDhBfl/Tka59a/QAm3vfIZrGAOu\r
bnMDIltxZiLZpgXIUHwE5BrcQjVP1gkq20rsR2Qf574XLazjWBujMjAwMB0GA1Ud\r
DgQWBBRGoN2+F9KKOUp7pMyAZ46JxmlY/zAPBgNVHRMBAf8EBTADAQH/MAoGCCqG\r
SM49BAMCA0kAMEYCIQDhkiDN+jIi4UhHroKQnMB+AV3Zl3wbQHPn7BkTs9PU6AIh\r
AJ1kn7vf32IyDJdwotbbUiEfU+6GPQgG2+IQquD1ElkF\r
-----END CERTIFICATE-----\r
"""
cert = """
-----BEGIN CERTIFICATE-----\r
MIIBUjCB+KADAgECAgkAikizPBBNMMYwCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwW\r
cmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEw\r
MTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDBZMBMG\r
ByqGSM49AgEGCCqGSM49AwEHA0IABLUhN9UhkH1dFm+V48ApmW3ym202QLFbNejQ\r
reM0SdpOD2sU91dgCBE3v3HmBxT6QL0ol50lVWfZlRv4LwPu+wGjFzAVMBMGA1Ud\r
EQQMMAqCCHBlZXIyLmZ5MAoGCCqGSM49BAMCA0kAMEYCIQD+nHKg0rNvkJFY1EBw\r
ffYplw17vIGV2Fb7bCWoYiAPxwIhAKeqZ8WxnIWzKgrcQhDh2WvTg02l9aM3zGiY\r
2Bm9LnOx\r
-----END CERTIFICATE-----\r
"""
grpc_port = 52000
listen_port = 40002
priv_key = """
-----BEGIN PRIVATE KEY-----\r
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgVBXbwdq/6ANNNBVE\r
xOSIhzQGKbw5kBcC4jNK/vKiMNihRANCAAS1ITfVIZB9XRZvlePAKZlt8pttNkCx\r
WzXo0K3jNEnaTg9rFPdXYAgRN79x5gcU+kC9KJedJVVn2ZUb+C8D7vsB\r
-----END PRIVATE KEY-----\r
"""
reconnect_timeout = 5

[[network_tls.peers]]
domain = 'peer0.fy'
host = 'localhost'
port = 40000

[[network_tls.peers]]
domain = 'peer1.fy'
host = 'localhost'
port = 40001

[[network_tls.peers]]
domain = 'peer3.fy'
host = 'localhost'
port = 40003

