[controller]
network_port = 51000
controller_port = 51004
consensus_port = 51001
storage_port = 51003
kms_port = 51005
executor_port = 51002
node_address = "0xd15373d1a0365d8491f4bede2e2d3863cca8e45d"

[genesis_block]
timestamp = 1633765324292
prevhash = "0x0000000000000000000000000000000000000000000000000000000000000000"

[system_config]
version = 0
chain_id = "0x26b0b83e7281be3b117658b6f2636d0368cad3d74f22243428f5401a4b70897e"
admin = "0xe7b14f079c1db897568883f0323af5887c2feebb"
block_interval = 3
validators = [ "0x47bfe5185471c7ded9ead15e4c768202c6d561e6", "0xd15373d1a0365d8491f4bede2e2d3863cca8e45d", "0x3f05a198b46179aa54115ab246f07c9417ce9ec9", "0x2e3bef28673715063bdc3b82d9a33fa96f959811",]
block_limit = 100

[consensus]
node_addr = "0xd15373d1a0365d8491f4bede2e2d3863cca8e45d"
grpc_listen_port = 51001
network_port = 51000
controller_port = 51004

[network_p2p]
port = 40001
grpc_port = 51000

[[network_p2p.peers]]
address = "/ip4/127.0.0.1/tcp/40000"

[[network_p2p.peers]]
address = "/ip4/127.0.0.1/tcp/40002"

[[network_p2p.peers]]
address = "/ip4/127.0.0.1/tcp/40003"

[kms_sm]
kms_port = 51005

[storage_rocksdb]
kms_port = 51005
storage_port = 51003

[executor_evm]
executor_port = 51002
[network_tls]
ca_cert = """
-----BEGIN CERTIFICATE-----\r
MIIBbTCCARKgAwIBAgIIOYrSF77doEYwCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwW\r
cmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEw\r
MTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDBZMBMG\r
ByqGSM49AgEGCCqGSM49AwEHA0IABGTl2glsbjDhBfl/Tka59a/QAm3vfIZrGAOu\r
bnMDIltxZiLZpgXIUHwE5BrcQjVP1gkq20rsR2Qf574XLazjWBujMjAwMB0GA1Ud\r
DgQWBBRGoN2+F9KKOUp7pMyAZ46JxmlY/zAPBgNVHRMBAf8EBTADAQH/MAoGCCqG\r
SM49BAMCA0kAMEYCIQDhkiDN+jIi4UhHroKQnMB+AV3Zl3wbQHPn7BkTs9PU6AIh\r
AJ1kn7vf32IyDJdwotbbUiEfU+6GPQgG2+IQquD1ElkF\r
-----END CERTIFICATE-----\r
"""
cert = """
-----BEGIN CERTIFICATE-----\r
MIIBUDCB+KADAgECAgkA/QbNkBh997MwCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwW\r
cmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEw\r
MTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDBZMBMG\r
ByqGSM49AgEGCCqGSM49AwEHA0IABBHygYoZ5CmT6TBbOdz6kIpZHHzLugeOcUHQ\r
ZtgeAgrc1w3d2r1krgnybDArniaDj5gKLFZ9uoNlwR7lZ9Xv4rCjFzAVMBMGA1Ud\r
EQQMMAqCCHBlZXIxLmZ5MAoGCCqGSM49BAMCA0cAMEQCICq+9Y2MCq4JMj4qcVzA\r
s6KZsUaUUrUKYMxjzS1MFf4gAiBdOQWqFYAwqf8HI+6ytawfTdY//Kx4l1g+Vgvi\r
C8x4lw==\r
-----END CERTIFICATE-----\r
"""
grpc_port = 51000
listen_port = 40001
priv_key = """
-----BEGIN PRIVATE KEY-----\r
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgNHAogE10kulBmwUZ\r
ubs+/FAR3GwbFBpu4/VQemJ9YOahRANCAAQR8oGKGeQpk+kwWznc+pCKWRx8y7oH\r
jnFB0GbYHgIK3NcN3dq9ZK4J8mwwK54mg4+YCixWfbqDZcEe5WfV7+Kw\r
-----END PRIVATE KEY-----\r
"""
reconnect_timeout = 5

[[network_tls.peers]]
domain = 'peer0.fy'
host = 'localhost'
port = 40000

[[network_tls.peers]]
domain = 'peer2.fy'
host = 'localhost'
port = 40002

[[network_tls.peers]]
domain = 'peer3.fy'
host = 'localhost'
port = 40003

